using System.Text.Json;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;
using Platform.Engineering.Copilot.Agents.Compliance.Tools;
using Platform.Engineering.Copilot.Core.Data.Enumerations;

namespace Platform.Engineering.Copilot.Tests.Unit.Tools.Compliance;

/// <summary>
/// T124 — Unit tests for ComplianceChatTool.
/// Message required, conversationId, NL interaction, conversation memory, no auth.
/// </summary>
public class ComplianceChatToolTests
{
    private readonly ComplianceChatTool _tool = new(
        new Mock<ILogger<ComplianceChatTool>>().Object);

    [Fact] public void Name_Is_Correct() => _tool.Name.Should().Be("compliance_chat");
    [Fact] public void RequiresAuthentication_Is_False() => _tool.RequiresAuthentication.Should().BeFalse();
    [Fact] public void PimTier_Is_None() => _tool.PimTierRequired.Should().Be(PimTier.None);

    [Fact]
    public async Task Valid_Message_Returns_Success()
    {
        var result = await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "What is NIST 800-53?"
        });
        var doc = JsonDocument.Parse(result);
        doc.RootElement.GetProperty("status").GetString().Should().Be("success");
        doc.RootElement.GetProperty("data").GetProperty("response").GetString()
            .Should().NotBeNullOrEmpty();
    }

    [Fact]
    public async Task ConversationId_Is_AutoGenerated_When_Omitted()
    {
        var result = await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "Hello"
        });
        var doc = JsonDocument.Parse(result);
        doc.RootElement.GetProperty("data").GetProperty("conversationId").GetString()
            .Should().NotBeNullOrEmpty();
    }

    [Fact]
    public async Task ConversationId_Is_Preserved_When_Provided()
    {
        var convId = "test-conv-123";
        var result = await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "Hello",
            ["conversationId"] = convId
        });
        var doc = JsonDocument.Parse(result);
        doc.RootElement.GetProperty("data").GetProperty("conversationId").GetString()
            .Should().Be(convId);
    }

    [Fact]
    public async Task Conversation_Memory_Tracks_Messages()
    {
        var convId = "memory-test";

        // First message
        await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "First message",
            ["conversationId"] = convId
        });

        // Second message
        var result = await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "Second message",
            ["conversationId"] = convId
        });

        var doc = JsonDocument.Parse(result);
        // 2 user messages + 2 assistant responses = 4
        doc.RootElement.GetProperty("data").GetProperty("messageCount").GetInt32()
            .Should().Be(4);
    }

    [Fact]
    public async Task Remediation_Topic_Returns_Board_Response()
    {
        var result = await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "Create a remediation board"
        });
        var doc = JsonDocument.Parse(result);
        doc.RootElement.GetProperty("data").GetProperty("response").GetString()
            .Should().Contain("remediation board");
        doc.RootElement.GetProperty("data").GetProperty("context")
            .GetProperty("topic").GetString().Should().Be("remediation");
    }

    [Fact]
    public async Task NIST_Topic_Returns_Relevant_Response()
    {
        var result = await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "Tell me about NIST 800-53"
        });
        var doc = JsonDocument.Parse(result);
        doc.RootElement.GetProperty("data").GetProperty("response").GetString()
            .Should().Contain("NIST");
        doc.RootElement.GetProperty("data").GetProperty("context")
            .GetProperty("topic").GetString().Should().Be("nist");
    }

    [Fact]
    public async Task SLA_Topic_Returns_Duration_Info()
    {
        var result = await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "What are the SLA due dates?"
        });
        var doc = JsonDocument.Parse(result);
        var response = doc.RootElement.GetProperty("data").GetProperty("response").GetString()!;
        response.Should().Contain("24 hours");
        response.Should().Contain("7 days");
    }

    [Fact]
    public async Task Response_Contains_Context_And_MessageCount()
    {
        var result = await _tool.ExecuteAsync(new Dictionary<string, object?>
        {
            ["message"] = "Hello compliance"
        });
        var doc = JsonDocument.Parse(result);
        var data = doc.RootElement.GetProperty("data");
        data.GetProperty("messageCount").GetInt32().Should().BeGreaterThan(0);
        data.GetProperty("context").GetProperty("topic").GetString()
            .Should().NotBeNullOrEmpty();
    }
}
