using System.Text;
using System.Linq;
using System.Collections.Generic;
using Platform.Engineering.Copilot.Core.Models;

namespace Platform.Engineering.Copilot.Core.Services.Generators.Bicep;

/// <summary>
/// Generates Azure App Service Bicep module files
/// Implements Azure best practices including Application Insights, Key Vault integration, and managed identity
/// </summary>
public class BicepAppServiceModuleGenerator
{
    /// <summary>
    /// Generate complete App Service module with app service plan, web app, and monitoring
    /// </summary>
    public Dictionary<string, string> GenerateAppServiceModule(TemplateGenerationRequest request)
    {
        var files = new Dictionary<string, string>();
        var serviceName = request.ServiceName.ToLowerInvariant();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var application = request.Application ?? new ApplicationSpec();
        
        var modulePath = "modules/appservice";
        
        // Generate module files
        files[$"{modulePath}/main.bicep"] = GenerateMainBicep(request);
        files[$"{modulePath}/app-service-plan.bicep"] = GenerateAppServicePlanBicep(request);
        files[$"{modulePath}/web-app.bicep"] = GenerateWebAppBicep(request);
        files[$"{modulePath}/application-insights.bicep"] = GenerateApplicationInsightsBicep(request);
        files[$"{modulePath}/key-vault.bicep"] = GenerateKeyVaultBicep(request);
        files[$"{modulePath}/private-endpoint.bicep"] = GeneratePrivateEndpointBicep(request);
        files[$"{modulePath}/parameters.json"] = GenerateParametersJson(request);
        
        // Optional: Networking
        if (infrastructure.IncludeNetworking == true)
        {
            files[$"{modulePath}/network.bicep"] = GenerateNetworkBicep(request);
        }
        
        return files;
    }
    
    private string GenerateMainBicep(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName.ToLowerInvariant();
        var application = request.Application ?? new ApplicationSpec();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var runtime = GetRuntimeStack(application.Language);
        var includeNetworking = infrastructure.IncludeNetworking == true;
        
        return $@"// App Service Module - Main Entry Point
// Generated by Platform Engineering Copilot

targetScope = 'resourceGroup'

@description('Name of the service')
param serviceName string

@description('Environment (dev, staging, prod)')
param environment string

@description('Azure region')
param location string = resourceGroup().location

@description('App Service Plan SKU')
@allowed([
  'B1'
  'B2'
  'B3'
  'S1'
  'S2'
  'S3'
  'P1v2'
  'P2v2'
  'P3v2'
  'P1v3'
  'P2v3'
  'P3v3'
])
param appServicePlanSku string = 'P1v3'

@description('Runtime stack')
param runtimeStack string = '{runtime}'

@description('Enable Application Insights')
param enableApplicationInsights bool = true

@description('Enable Always On')
param alwaysOn bool = true

@description('Enable HTTPS only')
param httpsOnly bool = true

@description('Enable VNet Integration')
param enableVnetIntegration bool = false

@description('Enable Private Endpoint')
param enablePrivateEndpoint bool = false

@description('FTP State')
@allowed(['AllAllowed', 'FtpsOnly', 'Disabled'])
param ftpsState string = 'FtpsOnly'

@description('Minimum TLS Version')
@allowed(['1.0', '1.1', '1.2', '1.3'])
param minTlsVersion string = '1.2'

@description('Enable Managed Identity')
param enableManagedIdentity bool = true

@description('Enable Client Certificate (Mutual TLS)')
param enableClientCertificate bool = false

@description('Client Certificate Mode')
@allowed(['Optional', 'OptionalInteractiveUser', 'Required'])
param clientCertMode string = 'Optional'

@description('Enable Detailed Error Messages')
param enableDetailedErrorMessages bool = false

@description('Enable HTTP Logging')
param enableHttpLogging bool = false

@description('IP Security Restrictions')
param ipSecurityRestrictions array = []

var commonTags = {{
  Environment: environment
  Service: serviceName
  ManagedBy: 'bicep'
  Platform: 'AppService'
}}

{(includeNetworking ? @"
// Network Infrastructure
module network './network.bicep' = {
  name: '${serviceName}-${environment}-network'
  params: {
    serviceName: serviceName
    location: location
    tags: commonTags
  }
}
" : "")}

// Application Insights
module applicationInsights './application-insights.bicep' = if (enableApplicationInsights) {{
  name: '${{serviceName}}-${{environment}}-appinsights'
  params: {{
    serviceName: serviceName
    environment: environment
    location: location
    tags: commonTags
  }}
}}

// Key Vault
module keyVault './key-vault.bicep' = {{
  name: '${{serviceName}}-${{environment}}-keyvault'
  params: {{
    serviceName: serviceName
    environment: environment
    location: location
    tags: commonTags
  }}
}}

// App Service Plan
module appServicePlan './app-service-plan.bicep' = {{
  name: '${{serviceName}}-${{environment}}-plan'
  params: {{
    serviceName: serviceName
    environment: environment
    location: location
    sku: appServicePlanSku
    tags: commonTags
  }}
}}

// Web App
module webApp './web-app.bicep' = {{
  name: '${{serviceName}}-${{environment}}-webapp'
  params: {{
    serviceName: serviceName
    environment: environment
    location: location
    appServicePlanId: appServicePlan.outputs.planId
    runtimeStack: runtimeStack
    applicationInsightsConnectionString: enableApplicationInsights ? applicationInsights.outputs.connectionString : ''
    applicationInsightsInstrumentationKey: enableApplicationInsights ? applicationInsights.outputs.instrumentationKey : ''
    keyVaultName: keyVault.outputs.keyVaultName
    alwaysOn: alwaysOn
    httpsOnly: httpsOnly
    enableVnetIntegration: enableVnetIntegration
    vnetSubnetId: {(includeNetworking ? "enableVnetIntegration ? network.outputs.appServiceSubnetId : ''" : "''")}
    enablePrivateEndpoint: enablePrivateEndpoint
    privateEndpointSubnetId: {(includeNetworking ? "enablePrivateEndpoint ? network.outputs.privateEndpointSubnetId : ''" : "''")}
    ftpsState: ftpsState
    minTlsVersion: minTlsVersion
    enableManagedIdentity: enableManagedIdentity
    enableClientCertificate: enableClientCertificate
    clientCertMode: clientCertMode
    enableDetailedErrorMessages: enableDetailedErrorMessages
    enableHttpLogging: enableHttpLogging
    ipSecurityRestrictions: ipSecurityRestrictions
    tags: commonTags
  }}
}}

// Grant Web App access to Key Vault
module keyVaultAccess 'br/public:avm/res/authorization/role-assignment:0.1.0' = {{
  name: '${{serviceName}}-${{environment}}-kv-access'
  params: {{
    principalId: webApp.outputs.systemAssignedIdentityPrincipalId
    roleDefinitionIdOrName: 'Key Vault Secrets User'
    principalType: 'ServicePrincipal'
  }}
}}

{(includeNetworking ? @"
// Private Endpoint (if enabled)
module privateEndpoint './private-endpoint.bicep' = if (enablePrivateEndpoint) {
  name: '${serviceName}-${environment}-pe'
  params: {
    serviceName: serviceName
    environment: environment
    location: location
    webAppId: webApp.outputs.webAppId
    subnetId: network.outputs.privateEndpointSubnetId
    virtualNetworkId: network.outputs.vnetId
    tags: commonTags
  }
}
" : "")}

// Outputs
output webAppUrl string = webApp.outputs.defaultHostName
output webAppName string = webApp.outputs.name
output appServicePlanId string = appServicePlan.outputs.planId
output applicationInsightsId string = enableApplicationInsights ? applicationInsights.outputs.id : ''
output keyVaultName string = keyVault.outputs.keyVaultName
output systemAssignedIdentityPrincipalId string = webApp.outputs.systemAssignedIdentityPrincipalId
{(includeNetworking ? @"output vnetId string = network.outputs.vnetId
output vnetName string = network.outputs.vnetName" : "")}
";
    }
    
    private string GenerateAppServicePlanBicep(TemplateGenerationRequest request)
    {
        return @"// App Service Plan Configuration
// Implements zone redundancy and auto-scaling

targetScope = 'resourceGroup'

param serviceName string
param environment string
param location string
param sku string
param tags object

var planName = '${serviceName}-${environment}-plan'

resource appServicePlan 'Microsoft.Web/serverfarms@2023-01-01' = {
  name: planName
  location: location
  tags: tags
  sku: {
    name: sku
  }
  kind: 'linux'
  properties: {
    reserved: true // Required for Linux
    zoneRedundant: contains(['P1v3', 'P2v3', 'P3v3'], sku) // Zone redundancy for Premium v3
    elasticScaleEnabled: contains(['P1v3', 'P2v3', 'P3v3'], sku)
    maximumElasticWorkerCount: 10
  }
}

// Auto-scale settings for production workloads
resource autoScaleSettings 'Microsoft.Insights/autoscalesettings@2022-10-01' = if (contains(['P1v3', 'P2v3', 'P3v3', 'P1v2', 'P2v2', 'P3v2'], sku)) {
  name: '${planName}-autoscale'
  location: location
  tags: tags
  properties: {
    enabled: true
    targetResourceUri: appServicePlan.id
    profiles: [
      {
        name: 'Default autoscale condition'
        capacity: {
          minimum: '1'
          maximum: '10'
          default: '2'
        }
        rules: [
          {
            metricTrigger: {
              metricName: 'CpuPercentage'
              metricResourceUri: appServicePlan.id
              timeGrain: 'PT1M'
              statistic: 'Average'
              timeWindow: 'PT5M'
              timeAggregation: 'Average'
              operator: 'GreaterThan'
              threshold: 70
            }
            scaleAction: {
              direction: 'Increase'
              type: 'ChangeCount'
              value: '1'
              cooldown: 'PT5M'
            }
          }
          {
            metricTrigger: {
              metricName: 'CpuPercentage'
              metricResourceUri: appServicePlan.id
              timeGrain: 'PT1M'
              statistic: 'Average'
              timeWindow: 'PT5M'
              timeAggregation: 'Average'
              operator: 'LessThan'
              threshold: 30
            }
            scaleAction: {
              direction: 'Decrease'
              type: 'ChangeCount'
              value: '1'
              cooldown: 'PT5M'
            }
          }
        ]
      }
    ]
  }
}

output planId string = appServicePlan.id
output planName string = appServicePlan.name
";
    }
    
    private string GenerateWebAppBicep(TemplateGenerationRequest request)
    {
        return @"// Web App Configuration
// Implements managed identity, deployment slots, and security best practices

targetScope = 'resourceGroup'

param serviceName string
param environment string
param location string
param appServicePlanId string
param runtimeStack string
param applicationInsightsConnectionString string
param applicationInsightsInstrumentationKey string
param keyVaultName string
param alwaysOn bool
param httpsOnly bool
param enableVnetIntegration bool = false
param vnetSubnetId string = ''
param enablePrivateEndpoint bool = false
param privateEndpointSubnetId string = ''
param ftpsState string = 'FtpsOnly'
param minTlsVersion string = '1.2'
param enableManagedIdentity bool = true
param enableClientCertificate bool = false
param clientCertMode string = 'Optional'
param enableDetailedErrorMessages bool = false
param enableHttpLogging bool = false
param ipSecurityRestrictions array = []
param tags object

var appName = '${serviceName}-${environment}'
var keyVaultUri = 'https://${keyVaultName}.vault.azure.net/'

resource webApp 'Microsoft.Web/sites@2023-01-01' = {
  name: appName
  location: location
  tags: tags
  kind: 'app,linux'
  identity: enableManagedIdentity ? {
    type: 'SystemAssigned'
  } : null
  properties: {
    serverFarmId: appServicePlanId
    httpsOnly: httpsOnly
    clientAffinityEnabled: false
    virtualNetworkSubnetId: enableVnetIntegration && !empty(vnetSubnetId) ? vnetSubnetId : null
    clientCertEnabled: enableClientCertificate
    clientCertMode: clientCertMode
    
    siteConfig: {
      linuxFxVersion: runtimeStack
      alwaysOn: alwaysOn
      ftpsState: ftpsState
      minTlsVersion: minTlsVersion
      http20Enabled: true
      detailedErrorLoggingEnabled: enableDetailedErrorMessages
      httpLoggingEnabled: enableHttpLogging
      
      // Health check
      healthCheckPath: '/health'
      
      // Application settings
      appSettings: [
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: applicationInsightsConnectionString
        }
        {
          name: 'ApplicationInsightsAgent_EXTENSION_VERSION'
          value: '~3'
        }
        {
          name: 'XDT_MicrosoftApplicationInsights_Mode'
          value: 'Recommended'
        }
        {
          name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
          value: applicationInsightsInstrumentationKey
        }
        {
          name: 'KEY_VAULT_URI'
          value: keyVaultUri
        }
        {
          name: 'ASPNETCORE_ENVIRONMENT'
          value: environment
        }
        {
          name: 'NODE_ENV'
          value: environment == 'prod' ? 'production' : 'development'
        }
      ]
      
      // CORS settings
      cors: {
        allowedOrigins: [
          '*' // Configure based on your requirements
        ]
        supportCredentials: false
      }
      
      // IP security restrictions
      ipSecurityRestrictions: !empty(ipSecurityRestrictions) ? ipSecurityRestrictions : [
        {
          action: 'Allow'
          priority: 100
          name: 'Allow all'
          ipAddress: 'Any'
        }
      ]
      
      // SCM IP security restrictions
      scmIpSecurityRestrictions: !empty(ipSecurityRestrictions) ? ipSecurityRestrictions : [
        {
          action: 'Allow'
          priority: 100
          name: 'Allow all'
          ipAddress: 'Any'
        }
      ]
    }
  }
}

// Staging slot for blue-green deployments
resource stagingSlot 'Microsoft.Web/sites/slots@2023-01-01' = {
  parent: webApp
  name: 'staging'
  location: location
  tags: tags
  kind: 'app,linux'
  identity: enableManagedIdentity ? {
    type: 'SystemAssigned'
  } : null
  properties: {
    serverFarmId: appServicePlanId
    httpsOnly: httpsOnly
    clientCertEnabled: enableClientCertificate
    clientCertMode: clientCertMode
    
    siteConfig: {
      linuxFxVersion: runtimeStack
      alwaysOn: alwaysOn
      ftpsState: ftpsState
      minTlsVersion: minTlsVersion
      detailedErrorLoggingEnabled: enableDetailedErrorMessages
      httpLoggingEnabled: enableHttpLogging
      
      appSettings: [
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: applicationInsightsConnectionString
        }
        {
          name: 'ASPNETCORE_ENVIRONMENT'
          value: 'Staging'
        }
        {
          name: 'KEY_VAULT_URI'
          value: keyVaultUri
        }
      ]
    }
  }
}

// Diagnostic settings
resource diagnosticSettings 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: '${appName}-diagnostics'
  scope: webApp
  properties: {
    logs: [
      {
        category: 'AppServiceHTTPLogs'
        enabled: true
      }
      {
        category: 'AppServiceConsoleLogs'
        enabled: true
      }
      {
        category: 'AppServiceAppLogs'
        enabled: true
      }
      {
        category: 'AppServicePlatformLogs'
        enabled: true
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
      }
    ]
  }
}

output name string = webApp.name
output id string = webApp.id
output webAppId string = webApp.id
output defaultHostName string = webApp.properties.defaultHostName
output systemAssignedIdentityPrincipalId string = enableManagedIdentity ? webApp.identity.principalId : ''
output stagingSlotName string = stagingSlot.name
output stagingSlotHostName string = stagingSlot.properties.defaultHostName
";
    }
    
    private string GenerateApplicationInsightsBicep(TemplateGenerationRequest request)
    {
        return @"// Application Insights Configuration
// Implements application performance monitoring

targetScope = 'resourceGroup'

param serviceName string
param environment string
param location string
param tags object

var appInsightsName = '${serviceName}-${environment}-ai'
var workspaceName = '${serviceName}-${environment}-logs'

// Log Analytics Workspace
resource workspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {
  name: workspaceName
  location: location
  tags: tags
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
  }
}

// Application Insights
resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  tags: tags
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: workspace.id
    IngestionMode: 'LogAnalytics'
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

output id string = applicationInsights.id
output name string = applicationInsights.name
output instrumentationKey string = applicationInsights.properties.InstrumentationKey
output connectionString string = applicationInsights.properties.ConnectionString
output workspaceId string = workspace.id
";
    }
    
    private string GenerateKeyVaultBicep(TemplateGenerationRequest request)
    {
        return @"// Key Vault Configuration
// Implements secrets management with RBAC

targetScope = 'resourceGroup'

param serviceName string
param environment string
param location string
param tags object

var keyVaultName = take(replace('${serviceName}-${environment}-kv', '-', ''), 24)

resource keyVault 'Microsoft.KeyVault/vaults@2023-02-01' = {
  name: keyVaultName
  location: location
  tags: tags
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enablePurgeProtection: true
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow' // Can be restricted to specific networks
    }
  }
}

// Example secret
resource databaseConnectionString 'Microsoft.KeyVault/vaults/secrets@2023-02-01' = {
  parent: keyVault
  name: 'database-connection-string'
  properties: {
    value: 'placeholder-update-via-pipeline'
    contentType: 'text/plain'
  }
}

output keyVaultId string = keyVault.id
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
";
    }
    
    private string GenerateParametersJson(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName.ToLowerInvariant();
        var application = request.Application ?? new ApplicationSpec();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var observability = request.Observability ?? new ObservabilitySpec();
        var runtime = GetRuntimeStack(application.Language);
        
        // Determine intelligent defaults
        var isProduction = request.TemplateType?.ToLower().Contains("prod") ?? false;
        var enableAppInsights = observability.ApplicationInsights || observability.StructuredLogging;
        
        return $@"{{
  ""$schema"": ""https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#"",
  ""contentVersion"": ""1.0.0.0"",
  ""parameters"": {{
    ""serviceName"": {{
      ""value"": ""{serviceName}""
    }},
    ""environment"": {{
      ""value"": ""dev""
    }},
    ""location"": {{
      ""value"": ""{infrastructure.Region}""
    }},
    
    // === App Service Configuration ===
    ""appServicePlanSku"": {{
      ""value"": ""P1v3""
    }},
    ""runtimeStack"": {{
      ""value"": ""{runtime}""
    }},
    ""alwaysOn"": {{
      ""value"": true
    }},
    
    // === Security Parameters ===
    ""httpsOnly"": {{
      ""value"": true
    }},
    ""enableVnetIntegration"": {{
      ""value"": {isProduction.ToString().ToLower()}
    }},
    ""vnetSubnetId"": {{
      ""value"": """"
    }},
    ""enablePrivateEndpoint"": {{
      ""value"": {isProduction.ToString().ToLower()}
    }},
    ""ftpsState"": {{
      ""value"": ""FtpsOnly""
    }},
    ""minTlsVersion"": {{
      ""value"": ""1.2""
    }},
    ""enableManagedIdentity"": {{
      ""value"": true
    }},
    
    // === Monitoring Parameters ===
    ""enableApplicationInsights"": {{
      ""value"": {enableAppInsights.ToString().ToLower()}
    }},
    ""enableDetailedErrorMessages"": {{
      ""value"": false
    }},
    ""enableHttpLogging"": {{
      ""value"": {enableAppInsights.ToString().ToLower()}
    }},
    
    // === Advanced Security ===
    ""enableClientCertificate"": {{
      ""value"": false
    }},
    ""clientCertMode"": {{
      ""value"": ""Optional""
    }},
    ""ipSecurityRestrictions"": {{
      ""value"": []
    }}
  }}
}}
";
    }
    
    private string GeneratePrivateEndpointBicep(TemplateGenerationRequest request)
    {
        return @"// Private Endpoint for App Service
targetScope = 'resourceGroup'

param serviceName string
param environment string
param location string
param webAppId string
param subnetId string
param virtualNetworkId string
param tags object

var privateEndpointName = '${serviceName}-${environment}-pe'
var privateDnsZoneName = 'privatelink.azurewebsites.net'
var pvtEndpointDnsGroupName = '${privateEndpointName}/default'

resource privateEndpoint 'Microsoft.Network/privateEndpoints@2023-05-01' = {
  name: privateEndpointName
  location: location
  tags: tags
  properties: {
    subnet: {
      id: subnetId
    }
    privateLinkServiceConnections: [
      {
        name: '${serviceName}-${environment}-plsc'
        properties: {
          privateLinkServiceId: webAppId
          groupIds: ['sites']
        }
      }
    ]
  }
}

resource privateDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' = {
  name: privateDnsZoneName
  location: 'global'
  tags: tags
}

resource privateDnsZoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = {
  parent: privateDnsZone
  name: '${serviceName}-${environment}-dns-link'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: {
      id: virtualNetworkId
    }
  }
}

resource pvtEndpointDnsGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-05-01' = {
  name: pvtEndpointDnsGroupName
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'config1'
        properties: {
          privateDnsZoneId: privateDnsZone.id
        }
      }
    ]
  }
  dependsOn: [
    privateEndpoint
  ]
}

output privateEndpointId string = privateEndpoint.id
output privateDnsZoneId string = privateDnsZone.id
";
    }
    
    private string GenerateNetworkBicep(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName.ToLowerInvariant();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var networkConfig = infrastructure.NetworkConfig ?? CreateDefaultNetworkConfig();
        
        // Check if using existing network or creating new
        if (networkConfig.Mode == NetworkMode.UseExisting)
        {
            return GenerateExistingNetworkReferencesBicep(networkConfig);
        }
        
        var sb = new StringBuilder();
        
        sb.AppendLine("// Network Configuration for App Service");
        sb.AppendLine("// Generated by Platform Engineering Copilot");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("@description('Service name')");
        sb.AppendLine("param serviceName string");
        sb.AppendLine();
        sb.AppendLine("@description('Location for all resources')");
        sb.AppendLine("param location string = resourceGroup().location");
        sb.AppendLine();
        sb.AppendLine("@description('Tags to apply to resources')");
        sb.AppendLine("param tags object = {}");
        sb.AppendLine();
        
        // VNet parameters
        sb.AppendLine($"@description('Virtual Network name')");
        sb.AppendLine($"param vnetName string = '{networkConfig.VNetName}'");
        sb.AppendLine();
        sb.AppendLine($"@description('Virtual Network address space')");
        sb.AppendLine($"param vnetAddressSpace string = '{networkConfig.VNetAddressSpace}'");
        sb.AppendLine();
        
        // DDoS Protection (if enabled)
        if (networkConfig.EnableDDoSProtection)
        {
            sb.AppendLine("@description('Enable DDoS Protection')");
            sb.AppendLine($"param enableDDoSProtection bool = {networkConfig.EnableDDoSProtection.ToString().ToLower()}");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(networkConfig.DDoSProtectionPlanId))
            {
                sb.AppendLine("@description('DDoS Protection Plan ID')");
                sb.AppendLine($"param ddosProtectionPlanId string = '{networkConfig.DDoSProtectionPlanId}'");
                sb.AppendLine();
            }
        }
        
        // Virtual Network
        sb.AppendLine("// Virtual Network");
        sb.AppendLine("resource vnet 'Microsoft.Network/virtualNetworks@2023-05-01' = {");
        sb.AppendLine("  name: vnetName");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    addressSpace: {");
        sb.AppendLine("      addressPrefixes: [vnetAddressSpace]");
        sb.AppendLine("    }");
        
        if (networkConfig.EnableDDoSProtection && !string.IsNullOrEmpty(networkConfig.DDoSProtectionPlanId))
        {
            sb.AppendLine("    enableDdosProtection: enableDDoSProtection");
            sb.AppendLine("    ddosProtectionPlan: {");
            sb.AppendLine("      id: ddosProtectionPlanId");
            sb.AppendLine("    }");
        }
        
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        
        // Subnets
        var appServiceSubnet = networkConfig.Subnets.FirstOrDefault(s => 
            s.Name.Contains("appservice") || s.Delegation == "Microsoft.Web/serverFarms");
        if (appServiceSubnet == null)
        {
            appServiceSubnet = new SubnetConfiguration
            {
                Name = "appservice-subnet",
                AddressPrefix = "10.0.1.0/24",
                Delegation = "Microsoft.Web/serverFarms"
            };
        }
        
        sb.AppendLine("// Subnet for App Service VNet Integration");
        sb.AppendLine("resource appServiceSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' = {");
        sb.AppendLine("  parent: vnet");
        sb.AppendLine($"  name: '{appServiceSubnet.Name}'");
        sb.AppendLine("  properties: {");
        sb.AppendLine($"    addressPrefix: '{appServiceSubnet.AddressPrefix}'");
        
        if (appServiceSubnet.EnableServiceEndpoints && appServiceSubnet.ServiceEndpoints.Any())
        {
            sb.AppendLine("    serviceEndpoints: [");
            foreach (var endpoint in appServiceSubnet.ServiceEndpoints)
            {
                sb.AppendLine($"      {{ service: '{endpoint}' }}");
            }
            sb.AppendLine("    ]");
        }
        
        sb.AppendLine("    delegations: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'appservice-delegation'");
        sb.AppendLine("        properties: {");
        sb.AppendLine($"          serviceName: '{appServiceSubnet.Delegation ?? "Microsoft.Web/serverFarms"}'");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        
        // Private Endpoint Subnet (if enabled)
        if (networkConfig.EnablePrivateEndpoint)
        {
            var privateSubnet = networkConfig.Subnets.FirstOrDefault(s => s.Name == networkConfig.PrivateEndpointSubnetName);
            if (privateSubnet == null)
            {
                privateSubnet = new SubnetConfiguration
                {
                    Name = networkConfig.PrivateEndpointSubnetName,
                    AddressPrefix = "10.0.2.0/24"
                };
            }
            
            sb.AppendLine("// Subnet for Private Endpoints");
            sb.AppendLine("resource privateEndpointSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' = {");
            sb.AppendLine("  parent: vnet");
            sb.AppendLine($"  name: '{privateSubnet.Name}'");
            sb.AppendLine("  properties: {");
            sb.AppendLine($"    addressPrefix: '{privateSubnet.AddressPrefix}'");
            sb.AppendLine("    privateEndpointNetworkPolicies: 'Disabled'");
            
            if (privateSubnet.EnableServiceEndpoints && privateSubnet.ServiceEndpoints.Any())
            {
                sb.AppendLine("    serviceEndpoints: [");
                foreach (var endpoint in privateSubnet.ServiceEndpoints)
                {
                    sb.AppendLine($"      {{ service: '{endpoint}' }}");
                }
                sb.AppendLine("    ]");
            }
            
            sb.AppendLine("  }");
            sb.AppendLine("  dependsOn: [appServiceSubnet]");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        // Network Security Group (if enabled)
        if (networkConfig.EnableNetworkSecurityGroup)
        {
            sb.AppendLine("// Network Security Group");
            sb.AppendLine("resource nsg 'Microsoft.Network/networkSecurityGroups@2023-05-01' = {");
            sb.AppendLine("  name: 'nsg-${serviceName}'");
            sb.AppendLine("  location: location");
            sb.AppendLine("  tags: tags");
            sb.AppendLine("  properties: {");
            sb.AppendLine("    securityRules: [");
            
            if (networkConfig.NsgRules.Any())
            {
                foreach (var rule in networkConfig.NsgRules)
                {
                    sb.AppendLine("      {");
                    sb.AppendLine($"        name: '{rule.Name}'");
                    sb.AppendLine("        properties: {");
                    sb.AppendLine($"          priority: {rule.Priority}");
                    sb.AppendLine($"          direction: '{rule.Direction}'");
                    sb.AppendLine($"          access: '{rule.Access}'");
                    sb.AppendLine($"          protocol: '{rule.Protocol}'");
                    sb.AppendLine($"          sourcePortRange: '{rule.SourcePortRange}'");
                    sb.AppendLine($"          destinationPortRange: '{rule.DestinationPortRange}'");
                    sb.AppendLine($"          sourceAddressPrefix: '{rule.SourceAddressPrefix}'");
                    sb.AppendLine($"          destinationAddressPrefix: '{rule.DestinationAddressPrefix}'");
                    sb.AppendLine($"          description: '{rule.Description}'");
                    sb.AppendLine("        }");
                    sb.AppendLine("      }");
                }
            }
            else
            {
                // Default rule: Allow internet outbound
                sb.AppendLine("      {");
                sb.AppendLine("        name: 'AllowInternetOutbound'");
                sb.AppendLine("        properties: {");
                sb.AppendLine("          priority: 100");
                sb.AppendLine("          direction: 'Outbound'");
                sb.AppendLine("          access: 'Allow'");
                sb.AppendLine("          protocol: '*'");
                sb.AppendLine("          sourcePortRange: '*'");
                sb.AppendLine("          destinationPortRange: '*'");
                sb.AppendLine("          sourceAddressPrefix: '*'");
                sb.AppendLine("          destinationAddressPrefix: 'Internet'");
                sb.AppendLine("        }");
                sb.AppendLine("      }");
            }
            
            sb.AppendLine("    ]");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        // Private DNS Zone (if enabled)
        if (networkConfig.EnablePrivateEndpoint && networkConfig.EnablePrivateDns)
        {
            var dnsZone = !string.IsNullOrEmpty(networkConfig.PrivateDnsZoneName) 
                ? networkConfig.PrivateDnsZoneName 
                : "privatelink.azurewebsites.net";
                
            sb.AppendLine("// Private DNS Zone");
            sb.AppendLine("resource privateDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' = {");
            sb.AppendLine($"  name: '{dnsZone}'");
            sb.AppendLine("  location: 'global'");
            sb.AppendLine("  tags: tags");
            sb.AppendLine("}");
            sb.AppendLine();
            
            sb.AppendLine("// Link Private DNS Zone to VNet");
            sb.AppendLine("resource privateDnsZoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = {");
            sb.AppendLine("  parent: privateDnsZone");
            sb.AppendLine("  name: '${serviceName}-link'");
            sb.AppendLine("  location: 'global'");
            sb.AppendLine("  properties: {");
            sb.AppendLine("    registrationEnabled: false");
            sb.AppendLine("    virtualNetwork: {");
            sb.AppendLine("      id: vnet.id");
            sb.AppendLine("    }");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        // Outputs
        sb.AppendLine("// Outputs");
        sb.AppendLine("output vnetId string = vnet.id");
        sb.AppendLine("output vnetName string = vnet.name");
        sb.AppendLine("output appServiceSubnetId string = appServiceSubnet.id");
        
        if (networkConfig.EnablePrivateEndpoint)
        {
            sb.AppendLine("output privateEndpointSubnetId string = privateEndpointSubnet.id");
        }
        
        if (networkConfig.EnableNetworkSecurityGroup)
        {
            sb.AppendLine("output nsgId string = nsg.id");
        }
        
        if (networkConfig.EnablePrivateDns)
        {
            sb.AppendLine("output privateDnsZoneId string = privateDnsZone.id");
        }
        
        return sb.ToString();
    }
    
    private string GenerateExistingNetworkReferencesBicep(NetworkingConfiguration networkConfig)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// Reference Existing Network Resources");
        sb.AppendLine("// Generated by Platform Engineering Copilot");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        
        // Parameters
        sb.AppendLine("@description('Service name')");
        sb.AppendLine("param serviceName string");
        sb.AppendLine();
        sb.AppendLine("@description('Existing VNet name')");
        sb.AppendLine($"param vnetName string = '{networkConfig.ExistingVNetName}'");
        sb.AppendLine();
        sb.AppendLine("@description('Existing VNet resource group')");
        sb.AppendLine($"param vnetResourceGroup string = '{networkConfig.ExistingVNetResourceGroup}'");
        sb.AppendLine();
        sb.AppendLine("@description('Location for new resources')");
        sb.AppendLine("param location string = resourceGroup().location");
        sb.AppendLine();
        sb.AppendLine("@description('Tags to apply to resources')");
        sb.AppendLine("param tags object = {}");
        sb.AppendLine();
        
        // Reference existing VNet
        sb.AppendLine("// Reference existing Virtual Network");
        sb.AppendLine($"resource vnet 'Microsoft.Network/virtualNetworks@2023-05-01' existing = {{");
        sb.AppendLine($"  name: vnetName");
        sb.AppendLine($"  scope: resourceGroup(vnetResourceGroup)");
        sb.AppendLine("}");
        sb.AppendLine();
        
        // Find subnets
        var appSubnet = networkConfig.ExistingSubnets.FirstOrDefault(s => 
            s.Purpose == SubnetPurpose.Application || s.Name.Contains("appservice"));
        var peSubnet = networkConfig.ExistingSubnets.FirstOrDefault(s => 
            s.Purpose == SubnetPurpose.PrivateEndpoints || s.Name.Contains("private"));
        
        if (appSubnet != null)
        {
            sb.AppendLine("// Reference existing App Service subnet");
            sb.AppendLine($"resource appServiceSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' existing = {{");
            sb.AppendLine($"  parent: vnet");
            sb.AppendLine($"  name: '{appSubnet.Name}'");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        if (peSubnet != null && networkConfig.EnablePrivateEndpoint)
        {
            sb.AppendLine("// Reference existing Private Endpoint subnet");
            sb.AppendLine($"resource privateEndpointSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' existing = {{");
            sb.AppendLine($"  parent: vnet");
            sb.AppendLine($"  name: '{peSubnet.Name}'");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        // Optionally create NSG if needed
        if (networkConfig.EnableNetworkSecurityGroup && networkConfig.NsgRules.Any())
        {
            sb.AppendLine("// Network Security Group");
            sb.AppendLine($"resource nsg 'Microsoft.Network/networkSecurityGroups@2023-05-01' = {{");
            sb.AppendLine($"  name: 'nsg-${{serviceName}}'");
            sb.AppendLine($"  location: location");
            sb.AppendLine($"  tags: tags");
            sb.AppendLine($"  properties: {{");
            sb.AppendLine($"    securityRules: [");
            
            foreach (var rule in networkConfig.NsgRules)
            {
                sb.AppendLine($"      {{");
                sb.AppendLine($"        name: '{rule.Name}'");
                sb.AppendLine($"        properties: {{");
                sb.AppendLine($"          priority: {rule.Priority}");
                sb.AppendLine($"          direction: '{rule.Direction}'");
                sb.AppendLine($"          access: '{rule.Access}'");
                sb.AppendLine($"          protocol: '{rule.Protocol}'");
                sb.AppendLine($"          sourcePortRange: '{rule.SourcePortRange}'");
                sb.AppendLine($"          destinationPortRange: '{rule.DestinationPortRange}'");
                sb.AppendLine($"          sourceAddressPrefix: '{rule.SourceAddressPrefix}'");
                sb.AppendLine($"          destinationAddressPrefix: '{rule.DestinationAddressPrefix}'");
                sb.AppendLine($"          description: '{rule.Description}'");
                sb.AppendLine($"        }}");
                sb.AppendLine($"      }}");
            }
            
            sb.AppendLine($"    ]");
            sb.AppendLine($"  }}");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        // Outputs
        sb.AppendLine("// Outputs");
        sb.AppendLine("output vnetId string = vnet.id");
        
        if (appSubnet != null)
        {
            sb.AppendLine("output appServiceSubnetId string = appServiceSubnet.id");
        }
        
        if (peSubnet != null)
        {
            sb.AppendLine("output privateEndpointSubnetId string = privateEndpointSubnet.id");
        }
        
        if (networkConfig.EnableNetworkSecurityGroup && networkConfig.NsgRules.Any())
        {
            sb.AppendLine("output nsgId string = nsg.id");
        }
        
        return sb.ToString();
    }
    
    private NetworkingConfiguration CreateDefaultNetworkConfig()
    {
        return new NetworkingConfiguration
        {
            Mode = NetworkMode.CreateNew,
            VNetName = "vnet-${serviceName}",
            VNetAddressSpace = "10.0.0.0/16",
            Subnets = new List<SubnetConfiguration>
            {
                new SubnetConfiguration
                {
                    Name = "appservice-subnet",
                    AddressPrefix = "10.0.1.0/24",
                    Delegation = "Microsoft.Web/serverFarms",
                    Purpose = SubnetPurpose.Application
                },
                new SubnetConfiguration
                {
                    Name = "privateendpoints-subnet",
                    AddressPrefix = "10.0.2.0/24",
                    Purpose = SubnetPurpose.PrivateEndpoints
                }
            },
            EnableNetworkSecurityGroup = true,
            EnablePrivateEndpoint = true,
            EnableServiceEndpoints = false,
            EnableDDoSProtection = false,
            EnablePrivateDns = true,
            PrivateDnsZoneName = "privatelink.azurewebsites.net",
            PrivateEndpointSubnetName = "privateendpoints-subnet"
        };
    }
    
    private string GetRuntimeStack(ProgrammingLanguage language)
    {
        return language switch
        {
            ProgrammingLanguage.NodeJS => "NODE|20-lts",
            ProgrammingLanguage.Python => "PYTHON|3.11",
            ProgrammingLanguage.DotNet => "DOTNETCORE|8.0",
            ProgrammingLanguage.Java => "JAVA|17-java17",
            ProgrammingLanguage.PHP => "PHP|8.2",
            ProgrammingLanguage.Ruby => "RUBY|3.2",
            _ => "NODE|20-lts"
        };
    }
}
